apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80           # Porta do serviço (usada pelos clientes)
      targetPort: 80     # Porta do container
      nodePort: 30080    # Porta exposta no Node (pode ser omitida para gerar automática)
